support deno and upgrade dep
shigma/reggol pull request #3
Opened 2022-11-20 17:53 UTC by idanran

feat: support deno
chore: upgrade dep

2022-11-27 18:49 UTC, idanran commented
PTAL @shigma

2022-11-27 19:08 UTC, shigma requested changes
You should open a PR for supports-color first.

2022-11-27 19:23 UTC, idanran commented
> You should open a PR for supports-color first.

chalk/supports-color#141

2022-11-28 03:29 UTC, shigma commented
https://github.com/chalk/supports-color/pull/141#issuecomment-1327011420

My opinion is more or less the same.

2022-11-28 04:11 UTC, idanran commented
> https://github.com/chalk/supports-color/pull/141#issuecomment-1327011420
> 
> My opinion is more or less the same.

I don't want to deal with upstream issues anymore, when it can run as expected.

2022-11-28 05:05 UTC, shigma commented
> Deno supports Node.js packages. We are not going to add lots of custom code for Deno.

Same with me. I sounds stupid to pollute all the node.js users' codebase just because of deno bugs.

> I don't want to deal with upstream issues anymore, when it can run as expected.

Me too. So I choose to close this PR.

2022-11-28 05:05 UTC, closed without merging

2022-11-28 11:37 UTC, idanran commented
https://github.com/denoland/deno/issues/16848#issuecomment-1328905990
This is not a bug in polyfill. @shigma

2022-11-28 11:44 UTC, shigma commented
If the expected behavior of deno is to **NOT** support supports-color, then I don't think I should break that behavior either.

After all what you want is not common practice at all. If you have any problems, you should first appeal to deno instead of dumping garbage in the users' node_modules.

I will not respond to this question until deno or supports-color change their attitude. This isn't something I should be dealing with at all.

2022-11-28 11:47 UTC, idanran commented
> If the expected behavior of deno is to **NOT** support supports-color, then I don't think I should break that behavior either.
> 
> After all what you want is not common practice at all. If you have any problems, you should first appeal to deno instead of dumping garbage in the users' node_modules.
> 
> I will not respond to this question until deno or supports-color change their attitude. This isn't something I should be dealing with at all.

The expected behavior of deno is to support color, but to request unnecessary permissions.

2022-11-28 11:49 UTC, idanran commented
I will hold off on this part of the revision until supports-color changes their attitude.